@startuml

title __JAVA's Class Diagram__\n

    class Hint {
        ~ active : boolean
        ~ content : String
        + Hint()
        + getContent()
        + setActive()
    }

    class Logbook {
        ~ allHints : ArrayList<String>
        ~ core : PApplet
        ~ hintLines : ArrayList<String>
        ~ hintUrl : String
        ~ logbookActive : boolean
        ~ page : int
        ~ playerHints : ArrayList<Hint>
        ~ text : String
        + Logbook()
        + devEnableAll()
        + devPrintPlayerHints()
        + drawTextBox()
        + enableHint()
        + getHints()
        + hintsToLines()
        + loadAllHints()
        + setPlayerHints()
        ~ lineSplitter()
    }

    class Main {
        + bossMode : Boolean
        + quizMode : Boolean
        + startTime : long
        ~ allRooms : ArrayList<Room>
        + draw()
        + gameOver()
        + getImageFiles()
        + getInteractionFiles()
        + getKeyCode()
        + getTimeMin()
        + keyPressed()
        + keyReleased()
        + loadRooms()
        {static} + main()
        + mouseClicked()
        + settings()
        + setup()
        + triggerQuiz()
    }

    class Player {
        ~ attempts : int
        ~ core : PApplet
        ~ direction : String
        ~ health : int
        ~ heart : PImage
        ~ heartDeath : PImage
        ~ heartLife : PImage
        ~ interacting : int
        ~ moveDown : boolean
        ~ moveLeft : boolean
        ~ moveRight : boolean
        ~ moveUp : boolean
        ~ questionMark : PImage
        ~ sprite : PImage
        ~ spriteDown : PImage
        ~ spriteLeft : PImage
        ~ spriteRight : PImage
        ~ spriteUp : PImage
        ~ x : float
        ~ y : float
        + Player()
        + damage()
        + drawHUD()
        + drawPlayer()
        + interact()
        + movement()
        + setSprite()
        + triggerBoss()
    }

    class Quiz {
        ~ core : PApplet
        ~ correct : boolean
        ~ correctPlacement : float
        ~ level : int
        ~ levels : int
        ~ maxX : float
        ~ maxY : float
        ~ minX : float
        ~ minY : float
        ~ optionHover : boolean
        ~ quizNumber : int
        ~ results : boolean
        ~ resultsTimer : int
        ~ space : float
        ~ sphinx : PImage
        ~ success : boolean
        + Quiz()
        + activateBoss()
        + activateQuiz()
        + drawQuiz()
        + drawSphinx()
        + questionString()
        + quizOption()
        + shuffleOptions()
        ~ questionSplitter()
    }

    class Room {
        ~ background : PImage
        ~ core : PApplet
        ~ heightInTiles : int
        ~ id : int
        ~ interactionUrl : String
        ~ spaces : ArrayList<Space>
        ~ tileMap : PImage
        ~ tileSize : int
        ~ widthInTiles : int
        + Room()
        + bossTerritory()
        + coordToId()
        + drawRoom()
        + evalSpaces()
        + fillSpaces()
        + getInteraction()
        + setBackground()
        + setTileMap()
        + spaceDownSolid()
        + spaceInteraction()
        + spaceLeftSolid()
        + spaceRightSolid()
        + spaceUpSolid()
        + xFromId()
        + yFromId()
        ~ interactionSplitter()
    }

    class SoundController {
        ~ audioInputStream : AudioInputStream
        ~ clip : Clip
        ~ currentFrame : Long
        ~ filePath : String
        ~ status : String
        + SoundController()
        + play()
        + resetAudioStream()
    }

    class Space {
        ~ boss : boolean
        ~ core : PApplet
        ~ id : int
        ~ interaction : int
        ~ solid : boolean
        + Space()
        + getBoss()
        + getInteraction()
        + getSolid()
    }

    class TextBox {
        ~ core : PApplet
        ~ space : int
        ~ text : String
        + TextBox()
        + activateText()
        + drawTextBox()
        + sphinxMonologue()
    }
  

  Logbook o-- Main : main
  Main -up-|> processing.core.PApplet
  Main o-- SoundController : correct
  Main o-- Room : currentRoom
  Main o-- SoundController : interact
  Main o-- Logbook : l1
  Main o-- Player : p1
  Main o-- Quiz : q1
  Main o-- SoundController : wrong
  Player o-- Main : main
  Player o-- TextBox : t1
  Quiz o-- Main : main
  Room o-- Logbook : log
  Space o-- Room : r
  TextBox o-- Main : main


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
